# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            F. Marlétaz
tagline:          'Zoologist 2.0'
url:              http://fmarletaz.github.io
paginate:         1
baseurl:          /
author:
  name:           Ferdinand Marlétaz
  url:            https://twitter.com/ferdix
  email:          ferdinand.marletaz@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/fmarletaz/fmarletaz.github.io

# This is the list of pages to include in the header of the website.
pages_list:       
  About: '/about/'
  Research: '/Research/'
  Publications: '/Publications/'
  Feed: '/atom.xml'