# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Page
tagline:          Ferdinand Marlétaz 
url:              http://fmarletaz.github.io
paginate:         1
baseurl:          /
author:
  name:           Ferdinand Marlétaz
  url:            https://twitter.com/ferdix
  email:          ferdinand.marletaz@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/fmarletaz/fmarletaz.github.io
